### ISSUE TITLE
Summer and Multiplier for Optimizable objects

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#112]
### Problem
If we want to optimize `J(a, b, c) = f(a, b) + g(b, c)`, then neither` f.x ` nor  `g.x` really contains the full optimization space, so it would be good to have an object that combines the two, so that `J.x` contains `a, b` and `c`. In addition to combining all the optimizables, it would also simply expression objectives such as `Flux([coil_1, coil_2]) + CurveLength(coil1) + CurveLength(coil2)`, and avoid the user having to do the summation by hand.

### Demo Code
```
from simsopt.geo.curveobjectives import CurveLength, MinimumDistance
import numpy as np
import sys
import os
sys.path.append(os.path.join("..", "..", "tests", "geo"))
from surface_test_helpers import get_ncsx_data
curves, currents, ma = get_ncsx_data(Nt_coils=1)
J1 = CurveLength(curves[0])
J2 = CurveLength(curves[1])
J3 = MinimumDistance(curves, 1.0)
print(J1.J() + 2*J2.J() + J3.J())
J = J1 + 2.*J2 + J3
J.x # should contain np.concatenate((curves[0].x, curves[1].x, curves[2].x))
J.J() # should be equivalent to J1.J() + 2*J2.J() + J3.J()
```

**Comment by landreman** [comment]
Addressed by #182
