### ISSUE TITLE
Visualization optional dependencies

### ISSUE THREAD

**Issue by StanczakDominik** [hiddenSymmetries/simsopt#117]
I see Mayavi is used for plotting e.g. here: https://simsopt.readthedocs.io/en/latest/simsopt.geo.html#simsopt.geo.surface.Surface.plot

However, the Docker container does not include it. Would it perhaps make sense to add somewhere around

https://github.com/hiddenSymmetries/simsopt/blob/b3f3c3165d7ad9c333787e1ef2bd7ad08023a3b4/setup.cfg#L62-L69

a list of visualization package (matplotlib, mayavi, have I missed anything?) versions that work with the rest of the package?

Of course, I know mayavi can be a tough cookie to install due to its heavy VTK dependency. Matplotlib, at least, could be good candidate for now, especially for inclusion into the Docker image.

Whatcha think? :)

**Comment by mbkumar** [comment]
@StanczakDominik,

Thanks for the feedback. I added mayavi to the docker container. Mayavi and its requirements are also made optional requirements for simsopt. Matplotlib is made as a mandatory requirement.
