### ISSUE TITLE
VMEC python module error

### ISSUE THREAD

**Issue by zhisong** [hiddenSymmetries/simsopt#14]
I attempted to install VMEC python wrapper with cmake on our cluster GADI.

I encounter the following error when I try to run the simsopt unit tests.

```
test_init_from_file (mhd.test_vmec.VmecTests) ... STOP allocation error in fixaray: istat2
```

It seems some error is encountered during memory allocated. To make sure it is not a problem of memory size, I have asked for 240G of memory, which should be sufficient. Has anyone encountered similar problems before? Any suggestions?

The compiler is GCC 8.3. The modules I have used are 
```
1) pbs   2) intel-mkl/2019.3.199   3) python3/3.7.4   4) netcdf/4.7.3(default)   5) openmpi/4.0.3   6) cmake/3.18.2
```

**Comment by zhisong** [comment]
UPDATE:

The last test before this one also made use of VMEC and it turned out OK. 
```
test_init_defaults (mhd.test_vmec.VmecTests) ... In core.finalize
ok
```

I have printed out the error code of ```istat2```. It is ```5014```, which means trying to allocate the same array twice. I guess the VMEC memory is not freed appropriately from the last VMEC run.

**Comment by zhisong** [comment]
MORE UPDATE:

The arrays ```xm,xn,xm_nyq,xn_nyq``` are not deallocated. They are in the subroutine ```finalize()```, but it is never called. Should they be deallocated properly somewhere?

**Comment by landreman** [comment]
Are you using https://gitlab.com/mbkumar/VMEC2000? If so, try instead using my fork https://gitlab.com/mattland/VMEC2000 - the simsopt tests all pass in the CI using this fork. The mbkumar version is based on Wisconsin's version of VMEC, which differed a little from STELLOPT's VMEC in runvmec.f and fileout.f. I was getting similar errors to you with the Wisconsin version. In [this commit](https://gitlab.com/mattland/VMEC2000/-/commit/58680793f94c3866d5647704b03d941bbb52042a) I changed those 2 files to match STELLOPT's VMEC. (@mbkumar There is a pull request in your gitlab for these changes.)

**Comment by zhisong** [comment]
@landreman Thank you! The problem is now resolved. All simsopt tests are successful now.

**Comment by mbkumar** [comment]
@landreman merged your changes to mbkumar/VMEC2000.
