### ISSUE TITLE
System for saving and loading coil sets

### ISSUE THREAD

**Issue by landreman** [hiddenSymmetries/simsopt#204]
For coil optimization, it would be convenient to have a function that saves not only the curve shapes and currents, but also `nfp`, the Fourier order, number of quadrature points, the target surface, etc. There could be a corresponding function to load in this data. This would make it easier for users to plot and analyze the results of a coil optimization.

**Comment by mbkumar** [comment]
@landreman 
Now that simsopt has the capability to store data in JSON format, should we close this issue?
