### ISSUE TITLE
Name error in simsgeo

### ISSUE THREAD

**Issue by zhisong** [hiddenSymmetries/simsopt#21]
I found there is a name error `StelleratorSymmetricCylindricalFourierCurve` in `simsgeoapp` or `simsgeo` that crashes the code. It should be `StellaratorSymmetricCylindricalFourierCurve`.

**Comment by landreman** [comment]
The spelling was corrected recently, in a couple of commits from March 3. All tests (including geo ones) pass on the CI and my laptop, so I think the spelling should be consistent in master. Perhaps the crash you see could happen if the python part of simsopt in your repo is from after March 3 but the compiled simsgeopp part is from before? Can you try recompiling the simsgeo part by uninstalling via `pip uninstall simsopt` and then reinstall?

**Comment by zhisong** [comment]
Thanks Matt. I figured out I have a separate installation of simsgeopp from hiddenSymmetries/simsgeo repository. Once I removed that, the tests all pass.
