### ISSUE TITLE
Git submodules and python source distribution are not compatible

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#24]
Hello Florian,

When creating a source distribution of _simsopt_, it is not possible to include _.git_ file. Hence the git submodule feature won't work if someone uses the source distribution from _pypi_ to install _simsopt_. Instead could you use `FetchContent` feature of _CMake_.

This was a snippet of _CMake_ code I was using for one of my projects. 

```
include(FetchContent)

FetchContent_DECLARE(
	yaml_cpp
	GIT_REPOSITORY	https://github.com/jbeder/yaml-cpp.git
)
```

You could google more about it.

Bharat

**Comment by florianwechsung** [comment]
Mh, I'm not convinced by this. I have a repo PyROL that includes pybind11 as a submodule, and I can distribute that via pypi just fine, see here
https://bitbucket.org/pyrol/pyrol/src/master/
and here 
https://pypi.org/project/ROL/

What is the exact problem you're seeing?

**Comment by mbkumar** [comment]
I looked at the ROL project source code. They are redistributing pybind11 along with PyROL in the sdist. Do you want to include the source code of all the projects in the thirdproject folder in the simsopt sdist? In that case, could you please check if the licenses of those projects allow redistribution?

Thank you

**Comment by florianwechsung** [comment]
They are all BSD or MPL, so including their code with ours is fine.
