### ISSUE TITLE
New changes on main branch necessitate MPI usage

### ISSUE THREAD

**Issue by akaptano** [hiddenSymmetries/simsopt#242]
Hi all,

I recently merged the main branch into the permanent_magnets branch (on July 1) and unfortunately this has broken some things. It appears that the new changes make it necessary to use MPI on any of the example scripts and my permanent magnet optimization scripts now (1) requires "srun python ..." instead of just "python ..." to properly function and (2) runs out of memory on a single Cori Haswell node when using the srun version. And because I am using the srun command the error is vague about where the out-of-memory occurs. Any suggestions for how to proceed? Can I adapt the MPI logging stuff to figure out why I am running out of memory? 

Best,
Alan

**Comment by mbkumar** [comment]
The tests are not breaking on the CI. However the top level imports might have messed up something.  Are you using compiling your code on Cori?

**Comment by landreman** [comment]
Is it possible that the out-of-memory error comes from srun launching 32
copies of your script? Srun launches as many copies as the number of MPI
process specified in the job script, so I believe you should specify just 1
MPI rank per node.

**Comment by akaptano** [comment]
Thanks Matt, looks like this is it. What is confusing is that "srun python ..." runs fine on an interactive node but on a compute node I need "srun -n 1 python ...", and hopefully this means it is still utilizing the ntasks-per-node=68 in the openmpi parts of the code...
