### ISSUE TITLE
Porting simsopt to ppc64

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#245]
Summit at Oakridge Leadership computing facility (O-LCF) and its sister machine at Princeton, Traverse, are based on PowerPC 9. There is a great interest to run simsopt on these machines. At present, two issues are preventing the use of simsopt on these machines. 

1. Compiling Jax on PPC64. Jaxlib is officially not supported on PPC64, but there was some effort from DESC people to get Jaxlib compiled on Traverse. Rogerio also reported success compiling Jaxlib on ppc64. Alternatively, make jax optional. See #240.
2. Biot-Savart kernel used in simsopt makes heavy use of SIMD. Simsopt uses xsimd as the SIMD library. However xsimd is compatible with only x86-64 and ARM. There are few ways to tackle this problem
    I. Use an alternative library like EVE or NSIMD. EVE is only C++20 compatible. Both offer some support for ppc64 with NSIMD having better support.
    II. Make SIMD library optional for evaluating Biot-Savart kernel.

**Comment by mbkumar** [comment]
Hello Rogerio,

Thanks for the info. By pinning jax versions to <= 0.1.55 means we are going to use an almost 2 year old version. I am OK with it being a temporary solution, but we should find an alternative. Also if we are going to use jax v0.1.55, we should test the combination in the Extensive CI.

**Comment by mbkumar** [comment]
@rogeriojorge 
I have a working version of simsopt on powerpc. XSIMD dependency was replace with non-SIMD code. I tested it on Traverse @ Princeton and its working.

**Comment by mbkumar** [comment]
PR #292 which addresses this issue is now merged into master. Closing

**Comment by rmchurch** [comment]
What is the current suggestion for simsopt on ppc64le? Using an older version of jax (0.2.18) installed from source, I get errors running some simsopt examples because it appears `jax.Array` is for newer versions.

**Comment by mbkumar** [comment]
Did you apply the patch located at simsopt/patches/simsopt_ppc.patch?

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)

**Comment by rmchurch** [comment]
Great, using `git apply --reject patches/simsopt_ppc.patch` fixes the issue.
