### ISSUE TITLE
"ImportError: cannot import name" after installing simsopt with conda

### ISSUE THREAD

**Issue by SHenneberg** [hiddenSymmetries/simsopt#262]
I tried to install simsopt on my laptop with conda:

conda install -c hiddensymmetries simsopt

In python I can now import simsopt without any error messages and obtain the version for example:
>>> import simsopt; print(simsopt.__version__)
0.7.4

But I can't load anything from subpackages:

>>> from simsopt.objectives import SquaredFlux
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SquaredFlux' from 'simsopt.objectives'

Is this an installation issue? How can I fix this?

**Comment by landreman** [comment]
Which machine are you on? If it's a laptop or desktop, which OS?

Can you also provide the output of `conda list`?

Thanks.

**Comment by landreman** [comment]
This may be because the imports have been modified since v0.7.4. Try `from simsopt.objectives.fluxobjective import SquaredFlux` - does that work?

**Comment by SHenneberg** [comment]
Hi Matt,

You are right. `from simsopt.objectives.fluxobjective import SquaredFlux ` worked.
Do you know why conda installed an older version? 
I am on my laptop which is a linux machine (Manjaro Linux). 
My `conda list` output is:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.2.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cudatoolkit               11.7.0              hd8887f6_10    conda-forge
cudnn                     8.4.1.50             hed8a83a_0    conda-forge
deprecated                1.2.13             pyh6c4a22f_0    conda-forge
etils                     0.7.1              pyhd8ed1ab_0    conda-forge
f90nml                    1.4.3              pyhd8ed1ab_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2            py39h78fa15d_0    conda-forge
grpc-cpp                  1.46.4               h30feacc_6    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
jax                       0.3.17             pyhd8ed1ab_0    conda-forge
jaxlib                    0.3.15          cuda112py39hf9e344c_203    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libabseil                 20220623.0      cxx17_h48a1fff_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_2    conda-forge
libprotobuf               3.21.5               h6239696_0    conda-forge
libsqlite                 3.39.2               h753d276_1    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
monty                     2022.4.26          pyhd8ed1ab_0    conda-forge
mpc                       1.2.1                h9f54685_0    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
nccl                      2.14.3.1             h0800d71_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nptyping                  2.3.1              pyhd8ed1ab_0    conda-forge
numpy                     1.21.6           py39h18676bf_0    conda-forge
openssl                   3.0.5                h166bdaf_1    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pyevtk                    1.5.0              pyh8a188c0_0    conda-forge
python                    3.9.13          h2660328_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
randomgen                 1.23.1           py39hd257fcd_0    conda-forge
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
ruamel.yaml               0.17.21          py39hb9d737c_1    conda-forge
ruamel.yaml.clib          0.2.6            py39hb9d737c_1    conda-forge
scipy                     1.9.1            py39h8ba3f38_0    conda-forge
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
simsopt                   0.7.4            py39h6cd0baa_0    hiddensymmetries
sqlite                    3.39.2               h4ff8645_1    conda-forge
sympy                     1.10.1           py39hf3d152e_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
typish                    1.9.3              pyhd8ed1ab_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1           py39hb9d737c_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge


(I now managed to install the new version from the source code using pip install by just following (more or less) the wiki for the "Greifswald cluster". )

Thanks for your help.

**Comment by landreman** [comment]
Hi @SHenneberg , @mbkumar and I looked at this today, and part of the issue was that the conda package CI wasn't working during the last few releases, hence the version of the conda package was quite old. @mbkumar just created a new release, so now if you try again to install the conda package, the version should be v0.9.3, which should be current. Then `from simsopt.objectives import SquaredFlux` should work.
