### ISSUE TITLE
Building on Arch Linux in Anaconda

### ISSUE THREAD

**Issue by jonathanschilling** [hiddenSymmetries/simsopt#278]
Hi,

I had some trouble building `simsopt` on Arch Linux in an Anaconda environment, which might be interesting for you.
A problem occured when building `simsoptpp`. The `boost` include in `tracing.hpp` was not found, since the `Boost_INCLUDE_DIRS` were not forwarded by CMake/pybind11 to the compiler.
Here is the call that should have built the `tracing.cpp.o` object:
```bash
/home/jonathan/anaconda3/envs/simsopt/bin/x86_64-conda-linux-gnu-c++ -Dsimsoptpp_EXPORTS -I/data/jonathan/work/code/simsopt/thirdparty/xtensor/include -I/data/jonathan/work/code/simsopt/thirdparty/xtensor-python/include -I/data/jonathan/work/code/simsopt/thirdparty/xsimd/include -I/data/jonathan/work/code/simsopt/thirdparty/xtl/include -I/data/jonathan/work/code/simsopt/thirdparty/eigen -I/home/jonathan/.local/lib/python3.10/site-packages/numpy/core/include -I/data/jonathan/work/code/simsopt/src/simsoptpp -I/data/jonathan/work/code/simsopt/thirdparty/fmt/include -isystem /home/jonathan/anaconda3/envs/simsopt/include/python3.10 -isystem /data/jonathan/work/code/simsopt/thirdparty/pybind11/include -O3 -march=native -mfma -ffp-contract=fast -O3 -DNDEBUG -fPIC -fvisibility=hidden -flto -fno-fat-lto-objects -fopenmp -std=gnu++14 -MD -MT CMakeFiles/simsoptpp.dir/src/simsoptpp/tracing.cpp.o -MF CMakeFiles/simsoptpp.dir/src/simsoptpp/tracing.cpp.o.d -o CMakeFiles/simsoptpp.dir/src/simsoptpp/tracing.cpp.o -c /data/jonathan/work/code/simsopt/src/simsoptpp/tracing.cpp
```

Boost was found (indicated in the output above the cited call) at `/home/jonathan/anaconda3/envs/simsopt/include`, which is however not a system-wide include dir (hence the requirement for an explict mention of it on the compiler call), but also does not show up in the compiler call.

I was able to fix this by specifying (in `CMakeLists.txt`)
`set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "-I${Boost_INCLUDE_DIRS}")`
instead of
`target_include_directories(${PROJECT_NAME} PRIVATE ${Boost_INCLUDE_DIRS})`.

To my understanding, those two options should have almost in all cases exactly the same effects.
However, I seem to have managed to stumble into a weird edge case scenario where the effect of those two calls is not identical.

Any ideas?

**Comment by mbkumar** [comment]
Hello @jonathanschilling,

Somehow I missed this issue. Is this still relevant for you? If so, I can take a stab at it using a virtual machine.

Bharat

**Comment by jonathanschilling** [comment]
Hi @mbkumar ,
thanks for picking this up again. Indeed this is still relevant and it would be great if you could have a look into it. Let me know if you need further action from my side.
Thanks,  Jonathan
