### ISSUE TITLE
remove unneeded SPEC repo access in CI

### ISSUE THREAD

**Issue by jons-pf** [hiddenSymmetries/simsopt#334]
@mbkumar 
I think this step and the next one are not needed anymore, since SPEC has been open-sourced in the mean time:
https://github.com/hiddenSymmetries/simsopt/blob/caff25f8708bdff3e94fec9fb72861b21f561569/.github/workflows/docker.yml#L28

**Comment by mbkumar** [comment]
Addressed in #335
