### ISSUE TITLE
Additional codes in Docker container

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#336]
@rogeriojorge and @landreman,

Currently, we are installing VMEC, SPEC, booz_xform, and virtual casing modules in the Docker container. If we want more software packages to be added to the Docker container, please let me know.

**Comment by rogeriojorge** [comment]
I would add pyQSC and pyQIC
https://github.com/landreman/pyQSC
https://github.com/rogeriojorge/pyQIC
