### ISSUE TITLE
CurvePerturbed tests failing in CI

### ISSUE THREAD

**Issue by landreman** [hiddenSymmetries/simsopt#349]
With python 3.9 and 3.10, the `test_curveperturbed.py` tests are failing in the CI. The tests pass with python 3.8. The tests pass on my laptop using python 3.10.5. The extensive CI last passed [on Aug 16](https://github.com/hiddenSymmetries/simsopt/actions/runs/5877413846/job/15937500741), and first failed [on Aug 29](https://github.com/hiddenSymmetries/simsopt/actions/runs/6014263233/job/16313566474), noticed by @smiet in #348. The failures do not seem to be associated to any change in simsopt - the same error messages are now happening in all branches. The failing and succeeding jobs used the same versions of numpy and randomgen. There was an update to scipy from 1.11.1 to 1.11.2 in between - maybe this is relevant? [This issue](https://github.com/astropy/astropy/issues/15195) or [this issue](https://github.com/scipy/scipy/issues/19103) may possibly be related?

The branch `ml/20230902-debug-ci` prints some extra info for the failing tests, and reproduces the error in the simple CI rather than extensive CI. You can search [this log](https://github.com/hiddenSymmetries/simsopt/actions/runs/6060181209/job/16444071906) for `test_perturbed` to see the printed output. As this printed info shows, the failing assertions are not just slightly violating some tolerance, but are completely wrong.

**Comment by florianwechsung** [comment]
Seems like an issue with the computation of the matrix square root. The changes here https://github.com/hiddenSymmetries/simsopt/tree/fw/sqrtm_fix fix the tests locally for me, fingers crossed it passes the CI.

**Comment by mbkumar** [comment]
Can someone raise the issue with scipy?

**Comment by landreman** [comment]
Resolved by #350
