### ISSUE TITLE
Docker container containing SIMSOPT + SPEC + VMEC

### ISSUE THREAD

**Issue by florianwechsung** [hiddenSymmetries/simsopt#35]
VMEC2000 seems non-trivial to install, so it would greatly simplify things if we had a docker container with an installation of simsopt with all external codes

**Comment by landreman** [comment]
On this topic of containers, I've seen NERSC recommend that many-node python applications use containers + Shifter to avoid long start-up times (https://docs.nersc.gov/development/languages/python/nersc-python/). To use a container in Shifter I believe there are some considerations about permissions, discussed here: https://docs.nersc.gov/development/shifter/how-to-use/

**Comment by florianwechsung** [comment]
I was actually just thinking of this for local development and usage, e.g. a simple way for people to run the vmec examples that doesn't involve compiling vmec2000 by hand.

**Comment by landreman** [comment]
@mbkumar Can you be in charge of this? I agree with @florianwechsung that having a container with simsopt+vmec+booz_xform would be very helpful to some users. Including SPEC in the container may be touchy for now since the SPEC repo is private, unless Stuart et al can make it public.

**Comment by zhucaoxiang** [comment]
@landreman Stuart and I are working on making SPEC public. But it would take some time before everything is done. By the way, I remember that SPEC has a docker image (or maybe just docker environments) set up by Chris. The information can be found in the repo. Maybe you guys can take it as a reference. STELLOPT also has one, though I haven't looked at it for a while.

**Comment by mbkumar** [comment]
Sure. I have it on my to-do list.

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)

**Comment by mbkumar** [comment]
Pending things left:

1. Build a workflow for pushing docker
2. Install all the dependencies in the final image for editable install.

**Comment by mbkumar** [comment]
The recent change of moving to use SPEC wrapper complicates stuff for docker. For the time being, new versions of docker images will come without spec.

**Comment by mbkumar** [comment]
Closing this one because except for SPEC, it is complete.
