### ISSUE TITLE
Link to vmec repository and instruction

### ISSUE THREAD

**Issue by Shibabrat** [hiddenSymmetries/simsopt#369]
The link in the error from this line needs correction:

https://github.com/hiddenSymmetries/simsopt/blob/490282b392d1f497cda988e8495c7da2cdb48be0/src/simsopt/mhd/vmec.py#L311C30-L311C74

For more clarity, can we mention on the Installation page that one needs to build the VMEC python extension to use it within SIMSOPT? I only became aware of this step when I got the error message.

**Comment by landreman** [comment]
Thanks for pointing this out. These items are fixed in the latest 2 commits.
