### ISSUE TITLE
Strainopt tests

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#371]
@ejpaul 

Could you please check the tests in test_strainopt.py? In particular, I am confused with the `subtest_binormal_curvature` and `subtest_torsion`. You are not asserting any conditions and the setting of  `errf_old` variable is not clear.

**Comment by ejpaul** [comment]
Thanks, @mbkumar. I have created PR #373 to address this.

**Comment by mbkumar** [comment]
Fixed in #373
