### ISSUE TITLE
Put C++ class definition in header files

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#41]
@florianwechsung ,

Regarding simsgeocpp, I am wondering about the logic behind the unconventional way of defining the C++ classes in cpp files. Is there any limitation you encountered for defining the classes in header files and implementing the class methods in the corresponding cpp files? If not, could you please put the class definitions in header files and include only the header files in the cpp files? Small methods (one or two lines) are typically defined as inline methods in the class definition and so they also can be moved to header file if you want. You can keep the implementation of the rest of the class methods in the cpp files.

Bharat

**Comment by florianwechsung** [comment]
What do we gain from splitting this? A downside of this splitting is a fairly significant code duplication between hpp and cpp files.

**Comment by mbkumar** [comment]
Why do you think there will be a large code duplication? As far as advantages of splitting, here is [one article](https://www.cplusplus.com/articles/Gw6AC542/) I can think of. Another advantage is it would make it easier for future developers/co-developers to identify the class interface easily.

**Comment by florianwechsung** [comment]
Many of the function in surface.cpp and curve.cpp are just a single line of code. Wouldn't having the declaration in a separate file means duplicating the function signature, which makes up most of the code in those files?

**Comment by mbkumar** [comment]
Those could be inlined meaning they will be part of class definition. So
they move to header files. The larger methods remain in cpp files.

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)

**Comment by mbkumar** [comment]
Actually, all the methods are inlined now. Typically short methods are
inlined and bigger methods are implemented out of class definition.

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)

**Comment by florianwechsung** [comment]
I have made this separation in the BiotSavart code now. When I have some extra time I'll make similar changes to the surface and coil classes.

**Comment by mbkumar** [comment]
Cool. Thanks!

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)
