### ISSUE TITLE
Wrong syntax in logging statements

### ISSUE THREAD

**Issue by eguiraud-pf** [hiddenSymmetries/simsopt#435]
Hello,

the logging code here:

https://github.com/hiddenSymmetries/simsopt/blame/f6a8412047ad418ba287ee9c32c707802f064970/src/simsopt/mhd/boozer.py#L181-L182

seems wrong, and triggers the following exception when running with log level INFO:

```
    self.boozer.run()
  File "/home/devuser/.cache/pants/named_caches/pex_root/venvs/s/f700390b/venv/lib/python3.10/site-packages/simsopt/mhd/boozer.py", line 179, in run
    logger.info('mnmax:', wout.mnmax, ' len(xm):', len(wout.xm), ' len(xn):', len(wout.xn))
Message: 'mnmax:'
Arguments: (72, ' len(xm):', 72, ' len(xn):', 72)
```

You can see the syntax is wrong by running the following at the prompt (with `error` instead of `info` so the logging actually happens):

```
import logging
logging.error('mnmax:', 242, ' len(xm):', 24, ' len(xn):', 24)
```

**Comment by landreman** [comment]
@eguiraud-pf do you agree that #436 would resolve this?

**Comment by eguiraud-pf** [comment]
thanks for the quick reaction @landreman , it should, yes!

**Comment by eguiraud** [comment]
Hello, sorry to bother, would it be possible to release a version with this fix? :pray:

**Comment by landreman** [comment]
Ok, just created a release v1.6.4.

**Comment by eguiraud-pf** [comment]
Thank you very much!
