### ISSUE TITLE
Bug in surface_test_helpers.py

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#52]
Hello Florian,

Could you please take a look at line 71 in tests/geo/surface_test_helpers.py file? Next to raise there should be an exception. Instead, there is a string.

**Comment by mbkumar** [comment]
@andrewgiuliani,

Is the commit that fixes this issue merged into main branch?

**Comment by florianwechsung** [comment]
No not yet

**Comment by andrewgiuliani** [comment]
This has been fixed in the most recent merged PR

https://github.com/hiddenSymmetries/simsopt/blob/71d6d11523a0f9a38cd0bc3473661cb10ab82273/tests/geo/surface_test_helpers.py#L71

**Comment by mbkumar** [comment]
Thanks. 
I am closing this.
