### ISSUE TITLE
DOF Data handling between C++ side and DOFs panda data frame class 

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#65]
Come up with a scheme where DOFs panda frame class can handle data sharing between C++ classes.

**Comment by mbkumar** [comment]
This issue is broadened to include the cases where classes want to handle/store DOFs outside the graph optimizable framework. For such cases, the scheme agreed upon is that those classes define `set_dofs` and `get_dofs` methods for external handling of data. The `set_dofs` method if defined would be called by the graph framework to pass the modified DOFs for external handling. Another method, `recompute_bell` is added. This method is called whenever DOFs are modified in parent classes. The method implements the class specific behavior for recomputing the objectives of the class.

**Comment by mbkumar** [comment]
PR #100 implements the new behavior and converts the Curve and its subclasses to the graph framework.

**Comment by landreman** [comment]
Moot. Pandas no longer used, and there is a new system for managing data between Optimizable objects that store their own dofs.
