### ISSUE TITLE
Some questions regarding profiling.cpp

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#77]
@florianwechsung, @landreman 

Hello Florian,

I am not fully familiar with the purpose of the profiling executable generated during the building of simsopt. Is it only to profile the speed of the C++ code? Or do you want it to be part of the distribution?

At present, profiling is a mandatory target in the CMakeLists. If it is only for profiling the C++ code and should be limited to developers, could you please make it an optional target?

Profiling.cpp is not part of the source distribution and so, installing simsopt from sdist zip is failing to build (because profiling is a mandatory target). I'll fix it by adding profiling.cpp to MANIFEST.in. But if you make it an optional target, we don't have to make it part of the sdist. 

Finally regarding the location of profiling.cpp:
I am thinking of moving profiling/profiling.cpp to src/simsgeopp if you want it keep it a mandatory target. If it is an optional build, then we can keep the current layout or move the profiling folder to src folder to prevent an excessive number of folders at the root level.

**Comment by florianwechsung** [comment]
Made profiling an optional target and moved it into the src folder in #75
