### ISSUE TITLE
Auto versioning the code

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#91]
The current manual increment of the version string is not feasible in the long run. Instead, investigate tools like bumpversion and versioneer to increment the version.

**Comment by StanczakDominik** [comment]
There's also https://github.com/pypa/setuptools_scm/ that lets you pull the version from the git tag. Just leaving it here as another possibility.

**Comment by mbkumar** [comment]
@StanczakDominik 

Thanks! I got setuptools_scm working and PR #119 should add the auto-versioning capability.
